services:
  intranet:
    build:
      context: ./intranet
      dockerfile: Dockerfile
    image: page
    container_name: intranet
    restart: always
    hostname: intranet.konoha.br
    networks:
      - asa-network
  portal:
    build:
      context: ./portal/site
      dockerfile: Dockerfile
    image: index
    container_name: portal
    restart: always
    hostname: portal.konoha.br
    networks:
      - asa-network
  wordpress:
    build: 
        context: ./intranet/wordpress
        dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    volumes:
        - ./intranet/wordpress/src/:/var/www/html/wp-content/plugins
    networks:
        - asa-network
  db:
    image: mysql:5.7
    restart: always
    environment: 
        MYSQL_DATABASE: wpdb
        MYSQL_USER: wpuser
        MYSQL_PASSWORD: wppass
        MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes: 
      - db:/var/lib/mysql
    networks:
      - asa-network
  adminer:
    depends_on: 
      - db
    image: adminer
    restart: always
    ports: 
      - 8888:8080
    networks:
      - asa-network
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: dns
    container_name: dns
    hostname: ns1.konoha.br
    restart: always
    tty: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - asa-network 
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - intranet
      - wordpress
      - portal
    volumes: 
      - ./proxy/nginx/default.conf:/etc/nginx/conf.d/default.conf
#Docker Networks
networks:
  asa-network:
    driver: bridge
   
        
volumes: 
    db:
