services:
  intranet:
    build:
      context: ./intranet
      dockerfile: Dockerfile
    image: intranet
    container_name: intranet
    restart: always
    hostname: intranet.konoha.br/wordpress
    depends_on:
        - wordpress
    networks:
      - asa-network
  portal:
    build:
      context: ./portal/site
      dockerfile: Dockerfile
    image: index
    container_name: portal
    restart: always
    hostname: portal.konoha.br
    networks:
      - asa-network
  wordpress:
        build: 
            context: ./wordpress
            dockerfile: Dockerfile
        image: wordpress
        container_name: wordpress
        restart: always
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: wppass
            WORDPRESS_DB_NAME: wpdb
        volumes:
            - ./wordpress/src/:/var/www/html/wp-content/plugins
        networks:
            - asa-network
  dns:
      build:
        context: ./dns
        dockerfile: Dockerfile
      image: dns
      container_name: dns
      hostname: ns1.konoha.br
      restart: always
      tty: true
      ports:
        - "53:53/tcp"
        - "53:53/udp"
      networks:
        - asa-network 
  mail:
    build:
      context: ./mail
      dockerfile: Dockerfile
    image: mail
    container_name: mail
    hostname: mail.pb.br
    restart: always
    tty: true
    ports:
      - "25:25"
      - "587:587"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
    networks:
      - asa-network 
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - intranet
      - wordpress
      - portal
    networks:
      - asa-network
#Docker Networks
networks:
  asa-network:
    driver: bridge
